[build]
  command = "ng build --configuration production"
  publish = "dist/miahu-sorteo/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
