[build]
  command = "ng build --configuration production"
  publish = "dist/miahu-sorteo"

[build.environment]
  NODE_VERSION = "20.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
